<?php

/**
 *          ****************************************************************************
 *          **********************||  PORTALES PANEL ADMINISTRATIVO ||******************
 *          ****************************************************************************
 * 
 *          @date               2019-11-15
 *          @author             Bayman Burton <bayman@burtonservers.com>
 *          @copyright          2019-2020 Burton Technology https://burtonservers.com
 *          @license            https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License (GPL v3)
 *          International Registered Trademark & Property of Burton Technology  https://burtonservers.com
 * 
 *          This source file is subject to the GNU General Public License (GPL v3)
 *          that is bundled with this package in the file LICENSE.txt.
 *          It is also available through the world-wide-web at this URL:
 *          https://www.gnu.org/licenses/gpl-3.0.en.html
 *          If you did not receive a copy of the license and are unable to
 *          obtain it through the world-wide-web, please send an email
 *          to dev@burtonservers.com so we can send you a copy immediately.
 *          This software is built and distributed by Burton Technology https://burtonservers.com
 *          By using this software you are Aware it is strictly prohibited its comercial distribution or 
 *          modification of any aspect of the aplication
 *
 *          Desc:
 *          Custom admin dashboard for easy lightweight SPA deployment.
 * 
 *          WARNING
 *          Please do not edit this file or the aplication could stop working as intended, also
 *          any modifications will be overwritten by newer versions in the future
 *          
 */

//  DEBUG EN PANTALLA   //
error_reporting(E_ALL);
ini_set('display_errors', 1);

//  HABILITAMOS EL ACCESO PUBLICO PARA REALIZAR LLAMADAS AJAX DESDE DOMINIOS PUBLICOS   /
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Origin, Content-Type, Authorization, X-Auth-Token');
header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS');
header('Content-type: application/javascript; charset=utf-8');

//   RESCATAMOS TODO EL OUTPUT  //
/**  PARA IMPRIMIRLO EN JSON
 * $output = ob_get_contents(); ob_end_clean();
 */
ob_start();

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'assets/plugins/PHPMailer/src/Exception.php';
require 'assets/plugins/PHPMailer/src/PHPMailer.php';
require 'assets/plugins/PHPMailer/src/SMTP.php';

require 'assets/scripts/utils.php';
//require 'assets/scripts/conn.php';
require 'assets/scripts/c.php';

$json = array();

if ($_POST || $_GET) {
    if ($_POST['meth']) {
        $method =    broom('reg', $_POST['meth']);
    }
    if ($_GET['meth']) {
        $method = broom('reg', $_GET['meth']);
    }

    //          USUARIO INICIA SESION           //
    if ($method == 'login') {

        $username = broom('reg', $_POST["username"]);
        $password = hash('sha512', $_POST['password']);
        $apiuri = $_POST['apiuri'];
        error_log('/////////////////// ' . $password);
        ////            CONSULTAMOS EL USUARIO EN LA BASE DE DATOS A VER SI EXISTE              ////
        $query = " SELECT * "
            . "FROM gt_usuario "
            . "WHERE userUsuario = '" . $username . "'";
        //error_log('/////////////////// '. $password );
        $result = $c->query($query);
        if (!$result) {
            $json['scriptResp'] = "userqueryFail";
            $json['q'] = $query;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        $rows = $result->num_rows;
        $row = $result->fetch_array(MYSQLI_ASSOC);

        ////          RETORNAMOS UN JSON AL AJAX PARA ALIMENTAR EL JAVASCRIPT          ////

        if (($rows != 0) && (strcmp($row["userUsuario"], $username) == 0) && ($row['passUsuario'] == $password)) {

            //   VERIFICAMOS SI TIENE IMAGEN CARGADA || CARGAMOS IMAGEN PREDETERMINADA        //
            $isavatar = "assets/img/users/" . $row["idUsuario"] . ".jpg";
            if (file_exists($isavatar)) {
                $row['userImg'] = $apiuri . $isavatar;
            } else {
                $isavatar2 = "assets/img/users/" . $row["idUsuario"] . ".png";
                if (file_exists($isavatar2)) {
                    $row['userImg'] = $apiuri . $isavatar2;
                } else {
                    $row['userImg'] = $apiuri . "assets/img/users/default.jpg";
                }
            }
            $row['panelView'] = file_get_contents('modules/' . $row["panelUsuario"] . '/view.php');
            $row['login'] = "YES";

            $val_update = "UPDATE gt_usuario SET loginUsuario = '" . date('Y-m-d H:i:s') . "' WHERE idUsuario = '" . $row["idUsuario"] . "';";
            $val_result = $c->query($val_update) or die("{'scriptResp' : 'queryFailedd', 'query' : '" . $val_update . "'}");

            $json['userIntel'] = $row;
            $json['scriptResp'] = "match";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {


            $sql = "SELECT CODVENDEDOR,NOMVENDEDOR, PASSWORDWEB FROM VENDEDORES WHERE NOMVENDEDOR = '" . $_POST["username"] . "' AND PASSWORDWEB = '" . $_POST["password"] . "'";
            $pa1 = array();
            $op1 = array("scrollable" => SQLSRV_CURSOR_KEYSET);

            $re1 = sqlsrv_query($conexion, $sql, $pa1, $op1);
            if (sqlsrv_num_rows($re1) != 0) {
                while ($fila = sqlsrv_fetch_array($re1)) {
                    $row = [];
                    $row['panelView'] = file_get_contents('modules/home/view.php');
                    $row['login'] = "YES";
                    $row['panelUsuario'] = 'home';
                    $row['userImg'] = $apiuri . "assets/img/users/default.jpg";
                    $row['idUsuario'] = $fila['CODVENDEDOR'];;
                    $row['userUsuario'] = $fila['NOMVENDEDOR'];;
                    $row['nombreUsuario'] = $fila['NOMVENDEDOR'];;
                    $row['rolUsuario'] = 'Usuario';
                }

                $json['userIntel'] = $row;
                $json['scriptResp'] = "match";
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            }
            /* 
            $wsdlUrl = 'http://10.238.26.69:9298/Service1.asmx?wsdl';
            $client = new SoapClient($wsdlUrl);

            $params = new stdClass();
            $params->userName = $_POST['username'];
            $params->password = $_POST['password'];
            $params->date = date('Y-m-d H:i:s');
            $result = $client->GetVendedoresForLogin($params);
            $objs = json_decode($result->GetVendedoresForLoginResult, true);

            if ($objs['code'] == '200') {

                error_log('/////////////////// ' . print_r($objs, true));
                $row = [];
                $row['panelView'] = file_get_contents('modules/home/view.php');
                $row['login'] = "YES";
                $row['panelUsuario'] = 'home';
                $row['userImg'] = $apiuri . "assets/img/users/default.jpg";
                $row['idUsuario'] = $objs['vendedoresList'][0]['Codvendedor'];
                $row['userUsuario'] = $objs['vendedoresList'][0]['Nomvendedor'];
                $row['nombreUsuario'] = $objs['vendedoresList'][0]['Nomvendedor'];
                $row['rolUsuario'] = $objs['vendedoresList'][0]['Tipousuario'];

                $json['userIntel'] = $row;
                $json['scriptResp'] = "match";
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            } 
            */
            $json['scriptResp'] = "noMatch";
            $json['passwo'] = $password;
            $json['password'] = $row['passUsuario'];
            $json['q'] = $query;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          USUARIO INICIA SESION  CON GOOGLE         //
    if ($method == 'googlelogin') {

        $fullname = broom('reg', $_POST["fullname"]);
        $pic = $_POST['pic'];
        $email = $_POST['email'];

        $row = [];
        $row['idUsuario'] = $email;
        $row['rolUsuario'] = 'Administrador';
        $row['userImg'] = $pic;
        $row['nombreUsuario'] = $fullname;
        $row['temaUsuario'] = '1';
        $row['panelUsuario'] = 'home';

        $row['panelView'] = file_get_contents('modules/' . $row["panelUsuario"] . '/view.php');
        $row['login'] = "YES";

        $json['userIntel'] = $row;
        $json['scriptResp'] = "match";
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          GESTIONAR EL PANEL A MOSTRAR            //
    if ($method == 'loadPanel') {
        $panel = broom('reg', $_POST["panel"]);
        $user = broom('reg', $_POST["user"]);

        if ($panel == 'undefined') {
            $panelView = file_get_contents('assets/views/login.php');
            $json['scriptResp'] = "loaded";
            $json['panel'] = $panelView;
            $json['panelName'] = 'login';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $panelView = file_get_contents('modules/' . $panel . '/view.php');
        $panelcontrol = file_get_contents('modules/' . $panel . '/controller.php');
        //        $select = "UPDATE gt_usuario SET panelUsuario = '" . $panel . "' WHERE idUsuario = '" . $user . "'";
        //        $result = $c->query($select);

        $json['scriptResp'] = "loaded";
        $json['panel'] = $panelView;
        $json['control'] = $panelcontrol;
        $json['panelName'] = $panel;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          RETORNAR EL MENU LATERAL AUTORIZADO PARA EL USUARIO            //
    if ($method == 'showSideBar') {
        $user = $_POST["user"];

        if ($user == 'undefined') {
            $json['scriptResp'] = "error";
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        $isGoog = explode('@', $user);
        if ($isGoog[1]) {
            $viewSidebar = file_get_contents('assets/views/sidebarAdmin.php');
            $json['scriptResp'] = "loaded";
            $json['sideb'] = $viewSidebar;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
        /* $select = "SELECT *  FROM gt_usuario  WHERE idUsuario = '" . $user . "'";
        $result = $c->query($select);
        $row = $result->fetch_array(MYSQLI_ASSOC);

        if ($row['rolUsuario'] == 'Administrador') {
            $viewSidebar = file_get_contents('assets/views/sidebarAdmin.php');
        }
        if ($row['rolUsuario'] == 'Nuevo') {
            $viewSidebar = file_get_contents('assets/views/sidebarNot.php');
        } */

        $viewSidebar = file_get_contents('assets/views/sidebarAdmin.php');
        $json['scriptResp'] = "loaded";
        $json['sideb'] = $viewSidebar;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          GESTIONAR EL PANEL A MOSTRAR            //
    if ($method == 'construct') {

        $getJuice = file_get_contents('assets/scripts/juice.php');
        $video = getBGVideo();

        $json['scriptResp'] = "done";
        $json['view'] = $panelView;
        $json['video'] = $video;
        $json['juice'] = $getJuice;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          ALIMENTAR LOS INDICADORES            //
    if ($method == 'feedHome') {

        $json['scriptResp'] = "done";
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          ALIMENTAR LOS PORTALES            //
    if ($method == 'feedPortals') {
        $apiuri = $_POST['apiuri'];

        // TOTAL DE PORTALES //
        $query = "  SELECT * FROM gt_portals ";
        $result = $c->query($query);
        $rows = $result->num_rows;

        $htmlPorts = ' 
            
							<div class="col-sm-12 col-md-6 col-lg-3">
                            <div class="card bg-info">
                                <div class="card-body">
                                    <div class="d-flex no-block align-items-center">
                                        <div>
                                            <h6 class="text-white">Sales</h6>
                                            <h2 class="text-white m-0 font-weight-normal">25k</h2>
                                        </div>
                                        <div class="ml-auto">
                                            <span class="text-white display-6"><i class="fa fa-signal fa-2x"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
        ';
        if ($rows != 0) {
            while ($row = $result->fetch_array(MYSQLI_ASSOC)) {
                if ($row['deletedPortal'] == '0') {
                    if ($row['statusPortal'] == 'true') {
                        $stat = 'checked="checked"';
                        $status = 'Activo';
                    } else {
                        $stat = ' ';
                        $status = 'Inactivo';
                    }
                    $isshortName = '';
                    if (strlen($row['namePortal']) > strlen(substr($row['namePortal'], 0, 15))) {
                        $isshortName = '...';
                    }
                    $isshortAgent = '';
                    if (strlen($row['agentPortal']) > strlen(substr($row['agentPortal'], 0, 15))) {
                        $isshortAgent = '...';
                    }
                    $htmlPorts .= '
                    <div class="col-md-3">
                        <div class="card portalPanelCard anim" data-idPortal="' . $row['idPortal'] . '">
                            <div class="card-body">
                                <div class="card-box tilebox-one">
                                    <i class="icon-layers float-right text-muted"><i class="fa fa-wifi text-info" aria-hidden="true"></i></i>
                                    <h2 class="m-b-20">' . substr($row['namePortal'], 0, 15) . $isshortName . ' </h2>
                                    <span>Leads totales</span><span class="badge badge-primary marg5"> 0 </span> <br>
                                    <span>Visitas totales</span><span class="badge badge-primary marg5"> 0 </span><br>
                                    <span>Encargado: </span><span class="badge badge-primary marg5"> ' . substr($row['agentPortal'], 0, 15) . $isshortAgent . ' </span><br>
                                    
                                </div>
                                
                                <div class="visitor-list marg15">
                                    <div class="media m-0 mt-0 border-bottom">
                                        <img class="avatar brround avatar-md mr-3" alt="avatra-img" src="' . $apiuri . 'assets/img/port/' . $row['imgPortal'] . '">
                                        <div class="media-body">
                                            <label class="custom-switch marg15">
                                                <input disabled="disabled" type="checkbox" ' . $stat . ' name="custom-switch-checkbox" class="custom-switch-input" >
                                                <span class="custom-switch-indicator"></span>
                                                <span class="custom-switch-description text-white">' . $status . '</span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="p-4 b-t card-footer">
                                <div class="row text-center">
                                    <div class="col-6 border-right text-center">
                                        <div class="text-center">
                                            <a href="#" class="fw-500 editThisPortal">
                                                <i class="fa fa-pencil-square  mr-5"></i>Editar
                                                <div class="offscreen editPortalID">' . $row['idPortal'] . '</div>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-6 text-center">
                                        <a href="#" class="fw-500 deleteThisPortal">
                                            <i class="fa fa-times-circle  mr-5"></i>Eliminar
                                            <div class="offscreen deletePortalID">' . $row['idPortal'] . '</div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    ';
                    $shoingPortals = 1;
                }
            }
            if ($shoingPortals != 1) {
                $json['isEmpty'] = 'yes';
            }
        } else {
            $json['isEmpty'] = 'yes';
        }


        $json['scriptResp'] = "done";
        $json['html'] = $htmlPorts;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          CREAR UN NUEVO PORTAL            //
    if ($method == 'newPortal') {

        //** CARGAMOS LA IMAGEN DEL PORTAL
        $path = 'assets/img/port/';
        $directorio = opendir($path);

        /** CALCULAMOS EL NOMBRE CONSECUTIVO DE LA SIGUIENTE IMAGEN ESTE NOMBRE SE LE ASIGNA AL PORTAL EN LA BD*/
        $filename = 1;
        while ($archivo = readdir($directorio)) {
            if (!is_dir($archivo)) {
                $filename++;
            }
        }

        $file = $path . basename($_FILES["imgPortal"]["name"]);
        $filext = pathinfo($file, PATHINFO_EXTENSION);
        $fullFile = $path . $filename . '.' . $filext;

        if (move_uploaded_file($_FILES["imgPortal"]["tmp_name"], $fullFile)) {
            chmod($fullFile, 0666);

            /** FILTRAMOS LOS DATOS PARA EL PORTAL */
            $name = broom('text', $_POST['namePortal']);
            $img = $filename . '.' . $filext;
            $date = date('Y-m-d H:i:s');
            $agent = broom('spa', $_POST['agentPortal']);
            $status = broom('reg', $_POST['statusPortal']);
            $limit = broom('num', $_POST['limitPortal']);
            $url = broom('url', $_POST['urlPortal']);

            // AGREGAR PORTAL //
            $query = " INSERT INTO gt_portals ( namePortal, imgPortal, datePortal, agentPortal, statusPortal, lastUpdatedPortal, limitPortal, urlPortal, deletedPortal) ";
            $query .= "VALUES ('" . $name . "','" . $img . "','" . $date . "','" . $agent . "','" . $status . "','" . $date . "','" . $limit . "','" . $url . "', '0')";
            $result = $c->query($query);
            $portId = $c->insert_id;
            $queryNext = " INSERT INTO gt_portalDetail ( idPortal, titlePortal, bgPortal, formPortal, hasFbPortal, dateDetailPortal, redirPortal) ";
            $queryNext .= "VALUES ('$portId','Ingrese sus datos para continuar','1.jpg','" . addslashes($defaultPortalForm) . "','0','$date', 'https://burtonservers.com')";
            $resultNext = $c->query($queryNext);

            $json['scriptResp'] = "done";
            $json['msg'] = "Image Uploaded // Portal Created";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            $json['q'] = $query;
            $json['post'] = json_encode($_POST);
            $json['get'] = json_encode($_GET);
            $json['files'] = json_encode($_FILES);
            $json['name'] = $name;
            $json['namep'] = $_POST['namePortal'];
            $json['namef'] = broom('text', $_POST['namePortal']);
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "done";
            $json['error'] = 'errorImg';
            $json['post'] = json_encode($_POST);
            $json['files'] = json_encode($_FILES);
            $json['html'] = $htmlPorts;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          DEVOLVER LOS DATOS DEL PORTAL            //
    if ($method == 'getPortal') {
        $apiuri = $_POST['apiuri'];
        $idportal = broom('num', $_POST['idPortal']);

        // TOTAL DE PORTALES //
        $query = "  SELECT * FROM gt_portals p 
                INNER JOIN gt_portalDetail pd 
                    ON (p.idPortal = pd.idPortal) 
                WHERE p.idPortal = '$idportal' 
                ORDER BY pd.idDetail DESC
                LIMIT 1 ";
        $result = $c->query($query);
        $rows = $result->num_rows;

        if ($rows < 1) {
            $json['scriptResp'] = "error";
            $json['msg'] = 'portal not found';
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $row = $result->fetch_array(MYSQLI_ASSOC);
            $json['scriptResp'] = "done";
            $json['portalData'] = $row;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          EDITAR PORTAL LOS PORTALES            //
    if ($method == 'editPortal') {
        $apiUri = $_POST['apiuri'];
        $idportal = broom('num', $_POST['idPortal']);

        if ($_POST['editing'] == 'status') {
            $statusPortal = broom('reg', $_POST['statusPortal']);
            $queryNext = " UPDATE gt_portals SET statusPortal = '$statusPortal' WHERE idPortal = '$idportal' ";
            $resultNext = $c->query($queryNext);

            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        if ($_POST['editing'] == 'statusFB') {
            $statusHasFb = broom('reg', $_POST['statusHasFb']);
            if ($statusHasFb == 'true') {
                $hasfb = '1';
            } else {
                $hasfb = '0';
            }
            // OBTENER PORTAL //
            $query = "  SELECT * FROM gt_portals p 
                        INNER JOIN gt_portalDetail pd 
                            ON (p.idPortal = pd.idPortal) 
                        WHERE p.idPortal = '$idportal' 
                        ORDER BY pd.idDetail DESC
                        LIMIT 1 ";
            $result = $c->query($query);
            $row = $result->fetch_array(MYSQLI_ASSOC);
            $date = date('Y-m-d H:i:s');

            $queryNext = " INSERT INTO gt_portalDetail ( idPortal, titlePortal, bgPortal, formPortal, hasFbPortal, dateDetailPortal) ";
            $queryNext .= "VALUES ('" . $idportal . "','" . $row['titlePortal'] . "','" . $row['bgPortal'] . "','" . addslashes($row['formPortal']) . "','$hasfb','$date')";
            $resultNext = $c->query($queryNext);

            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        if ($_POST['editing'] == 'LogoIMG') {

            /** CALCULAMOS EL NOMBRE CONSECUTIVO DE LA SIGUIENTE IMAGEN ESTE NOMBRE SE LE ASIGNA AL PORTAL EN LA BD **/
            $path = 'assets/img/port/';
            $directorio = opendir($path);
            $filename = 1;
            while ($archivo = readdir($directorio)) {
                if (!is_dir($archivo)) {
                    $filename++;
                }
            }

            $file = $path . basename($_FILES["imgPortal"]["name"]);
            $filext = pathinfo($file, PATHINFO_EXTENSION);
            $fullFile = $path . $filename . '.' . $filext;

            if (move_uploaded_file($_FILES["imgPortal"]["tmp_name"], $fullFile)) {
                chmod($fullFile, 0666);

                $img = $filename . '.' . $filext;
                $queryNext = " UPDATE gt_portals SET imgPortal = '$img' WHERE idPortal = '$idportal' ";
                $resultNext = $c->query($queryNext);

                $json['scriptResp'] = "done";
                $json['imgPortal'] = $img;
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            }
        }

        if ($_POST['editing'] == 'BGIMG') {

            /** CALCULAMOS EL NOMBRE CONSECUTIVO DE LA SIGUIENTE IMAGEN ESTE NOMBRE SE LE ASIGNA AL PORTAL EN LA BD **/
            $path = 'assets/img/portbg/';
            $directorio = opendir($path);
            $filename = 1;
            while ($archivo = readdir($directorio)) {
                if (!is_dir($archivo)) {
                    $filename++;
                }
            }

            $file = $path . basename($_FILES["imgPortal"]["name"]);
            $filext = pathinfo($file, PATHINFO_EXTENSION);
            $fullFile = $path . $filename . '.' . $filext;

            if (move_uploaded_file($_FILES["imgPortal"]["tmp_name"], $fullFile)) {
                chmod($fullFile, 0666);

                $query = "  SELECT * FROM gt_portals p 
                        INNER JOIN gt_portalDetail pd 
                            ON (p.idPortal = pd.idPortal) 
                        WHERE p.idPortal = '$idportal' 
                        ORDER BY pd.idDetail DESC
                        LIMIT 1 ";
                $result = $c->query($query);
                $row = $result->fetch_array(MYSQLI_ASSOC);
                $date = date('Y-m-d H:i:s');
                $img = $filename . '.' . $filext;

                $queryNext = " INSERT INTO gt_portalDetail ( idPortal, titlePortal, bgPortal, formPortal, hasFbPortal, dateDetailPortal) ";
                $queryNext .= "VALUES ('" . $idportal . "','" . $row['titlePortal'] . "','$img','" . addslashes($row['formPortal']) . "','" . $row['hasFbPortal'] . "','$date')";
                $resultNext = $c->query($queryNext);

                $json['scriptResp'] = "done";
                $json['imgPortal'] = $img;
                $output = ob_get_contents();
                ob_end_clean();
                $json['output'] = $output;
                echo json_encode($json);
                return;
            }
        }

        if ($_POST['editing'] == 'Fields') {
            $namePortal = $_POST['namePortal'];
            $agentPortal = $_POST['agentPortal'];
            $urlPortal = $_POST['urlPortal'];
            $titlePortal = broom('text', $_POST['titlePortal']);
            $limitPortal = $_POST['limitPortal'];

            $queryNext = " UPDATE gt_portals SET namePortal = '$namePortal', agentPortal = '$agentPortal', urlPortal = '$urlPortal', limitPortal = '$limitPortal'  WHERE idPortal = '$idportal' ";
            $resultNext = $c->query($queryNext);

            $query = "  SELECT * FROM gt_portals p 
                        INNER JOIN gt_portalDetail pd 
                            ON (p.idPortal = pd.idPortal) 
                        WHERE p.idPortal = '$idportal' 
                        ORDER BY pd.idDetail DESC
                        LIMIT 1 ";
            $result = $c->query($query);
            $row = $result->fetch_array(MYSQLI_ASSOC);
            $date = date('Y-m-d H:i:s');

            $queryNext = " INSERT INTO gt_portalDetail ( idPortal, titlePortal, bgPortal, formPortal, hasFbPortal, dateDetailPortal) ";
            $queryNext .= "VALUES ('" . $idportal . "','$titlePortal','" . $row['bgPortal'] . "','" . addslashes($row['formPortal']) . "','" . $row['hasFbPortal'] . "','$date')";
            $resultNext = $c->query($queryNext);

            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }

        if ($_POST['editing'] == 'formPortal') {
            $code = $_POST['formPortal'];

            // OBTENER PORTAL //
            $query = "  SELECT * FROM gt_portals p 
                        INNER JOIN gt_portalDetail pd 
                            ON (p.idPortal = pd.idPortal) 
                        WHERE p.idPortal = '$idportal' 
                        ORDER BY pd.idDetail DESC
                        LIMIT 1 ";
            $result = $c->query($query);
            $row = $result->fetch_array(MYSQLI_ASSOC);
            $date = date('Y-m-d H:i:s');

            $queryNext = " INSERT INTO gt_portalDetail ( idPortal, titlePortal, bgPortal, formPortal, hasFbPortal, dateDetailPortal) ";
            $queryNext .= "VALUES ('" . $idportal . "','" . $row['titlePortal'] . "','" . $row['bgPortal'] . "','" . addslashes($code) . "','" . $row['hasFbPortal'] . "','$date')";
            $resultNext = $c->query($queryNext);

            $json['scriptResp'] = "done";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          ELIMINAR PORTAL LOS PORTALES            //
    if ($method == 'deletePortal') {
        $apiUri = $_POST['apiuri'];
        $idportal = broom('num', $_POST['idPortal']);
        $queryNext = " UPDATE gt_portals SET deletedPortal = '1' WHERE idPortal = '$idportal' ";
        $resultNext = $c->query($queryNext);

        $json['scriptResp'] = "done";
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //         GUARDAR NUEVA VISITA DE PORTAL            //
    if ($method == 'logVisit') {

        $date = date('Y-m-d H:i:s');
        $queryNext = " INSERT INTO gt_visits ( guidVisit, idLead, dateVisit, portalVisit, typeVisit) ";
        $queryNext .= " VALUES ('" . $_POST['gguid'] . "','0','" . $date . "','" . $_POST['portal'] . "','0')";
        $resultNext = $c->query($queryNext);

        $output = ob_get_contents();
        $json['post'] = json_encode($_POST);
        $json['get'] = json_encode($_GET);
        $json['files'] = json_encode($_FILES);
        $json['msg'] = "log visit";
        $json['output'] = $output;
        ob_end_clean();
        echo json_encode($json);
        return;
    }

    //         GUARDAR NUEVA SESION DE PORTAL            //
    if ($method == 'saveNewLead') {

        $date = date('Y-m-d H:i:s');
        $queryNext = " INSERT INTO gt_leads ( guidLead, dateLead, portalLead, nameLead, phoneLead, emailLead) ";
        $queryNext .= " VALUES ('" . $_POST['guid'] . "','" . $date . "','" . $_POST['portal'] . "','" . $_POST['name'] . "','" . $_POST['telephone'] . "','" . $_POST['email'] . "') ";
        $resultNext = $c->query($queryNext);

        if ($resultNext) {

            $row = [];
            $row['idLead'] = $c->insert_id;
            $row['guidLead'] = $_POST['guid'];
            $row['dateLead'] = $date;
            $row['portalLead'] = $_POST['portal'];
            $row['nameLead'] = $_POST['name'];
            $row['phoneLead'] = $_POST['telephone'];
            $row['emailLead'] = $_POST['email'];

            $json['scriptResp'] = "done";
            $json['action'] = "leadSaved";
            $json['leadMeta'] = $row;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "error";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          DEBUG           //
    if ($method == 'debug') {
        
        error_log('//////////////////  ///////////////////////////////');
        
        $order = $_GET['find'];
        $wsdlUrl = 'http://10.238.26.69:9298/Service1.asmx?wsdl';
        $client = new SoapClient($wsdlUrl);
        $params = new stdClass();
        //$params->CODIGOBARRAS = (int)$order;
        $result = $client->SaveReturnDetail($params);

        ob_end_clean();
        var_dump($result);
        var_dump($order);
        return;
    }

    //          GENCSV           //
    if ($method == 'newCSV') {

        $report = json_decode($_POST['data'], true);

        $path = 'assets/reports/' . $report['title'] . date('Ymd-His') . '.csv';
        $fp = fopen($path, 'w');

        $headers = explode(',', $report['headers']);
        if ($fp) {
            fputcsv($fp, $headers, ';');
            foreach ($report['dataCont'] as $repLine) {
                fputcsv($fp, explode(',', $repLine), ';');
            }
        }
        fclose($fp);

        $json['scriptResp'] = "done";
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        $json['rep'] = $report;
        $json['enlace'] = $path;
        echo json_encode($json);
        return;
    }

    //          REPORT           //
    if ($method == 'report') {
        $apiuri = $_POST['apiuri'];

        // USUARIOS ACTIVOS EN LA PLATAFORMA //
        $query = "SELECT * FROM public.user WHERE created_at >= '2019-11-11' and is_provider = 'f'";
        $result = pg_query($dbconn, $query);
        $treg = pg_fetch_all($result);
        $num_fields = count($treg);

        $headers = array('Nombre', 'Apellido', 'Email', 'Creado en', 'Telefono');

        $fp = fopen('php://output', 'w');
        if ($fp && $result) {
            fputcsv($fp, $headers, ';');
            foreach ($treg as $userReg) {
                $row = [];
                $row[] = $userReg['first_name'];
                $row[] = $userReg['last_name'];
                $row[] = $userReg['email'];
                $row[] = $userReg['created_at'];
                $row[] = $userReg['cell_phone_number'];
                fputcsv($fp, $row, ';');
            }
            header('Content-Type: text/csv; charset=utf-8');
            header("Content-Disposition: attachment; filename=usuariosregistrados" . date('Ymd-His') . ".csv");
            return;
        }

        $json['scriptResp'] = "noRep";
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }

    //          GUARDAR NUEVA TOMA           //
    if ($method == 'saveNewToma') {

        $date = date('Y-m-d H:i:s');
        $queryNext = " INSERT INTO gt_tomas ( userToma, fechaToma, objToma, statusToma) ";
        $queryNext .= " VALUES ('" . $_POST['userToma'] . "','" . $date . "','" . json_encode($_POST['inventario']) . "','1') ";
        $resultNext = $c->query($queryNext);

        if ($resultNext) {

            error_log('//////////////////   PRESO           ///////////////////////////////');
            $opts = array(
                'http' => array(
                    'user_agent' => 'PHPSoapClient'
                )
            );
            $context = stream_context_create($opts);
            $soapClientOptions = array(
                'stream_context' => $context,
                'cache_wsdl' => WSDL_CACHE_NONE
            );

            $wsdlUrl = 'http://10.238.26.69:9298/Service1.asmx?wsdl';
            $client = new SoapClient($wsdlUrl);

            error_log('//////////////////   POSSO           ///////////////////////////////');
            $params = new stdClass();
            $params->inventario = $_POST['inventario'];
            $result = $client->CreateInventarioFisico($params);


            $json['scriptResp'] = "done";
            $json['status'] = "saved";
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        } else {
            $json['scriptResp'] = "error";
            $json['q'] = $queryNext;
            $json['qer'] = $c->error;
            $output = ob_get_contents();
            ob_end_clean();
            $json['output'] = $output;
            echo json_encode($json);
            return;
        }
    }

    //          GUARDAR NUEVA TOMA           //
    if ($method == 'consultarDevol') {

        $order = $_POST['devolVal'];

        $wsdlUrl = 'http://10.238.26.69:9298/Service1.asmx?wsdl';
        $client = new SoapClient($wsdlUrl);

        error_log('//////////////////  ///////////////////////////////');
        $params = new stdClass();
        $params->numero = (int)$order;
        $result = $client->GetReturnOrdenByNumber($params);


        $json['scriptResp'] = "done";
        $json['resp'] = $result;
        $output = ob_get_contents();
        ob_end_clean();
        $json['output'] = $output;
        echo json_encode($json);
        return;
    }
}

//   Si no se llamó ningún método de la API     //
$output = ob_get_contents();
$json['post'] = json_encode($_POST);
$json['get'] = json_encode($_GET);
$json['files'] = json_encode($_FILES);
$json['msg'] = "Mute API";
$json['output'] = $output;
ob_end_clean();
echo json_encode($json);
return;
